<?php

namespace FDM\ChampBundle\Repository;

/**
 * AncienNomClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AncienNomClubRepository extends \Doctrine\ORM\EntityRepository
{
}
