<?php

namespace FDM\ChampBundle\Repository;

/**
 * ContratJoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratJoueurRepository extends \Doctrine\ORM\EntityRepository
{
}
