<?php

namespace FDM\ChampBundle\Repository;

/**
 * ContratEntraineurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratEntraineurRepository extends \Doctrine\ORM\EntityRepository
{
}
