<?php

namespace FDM\ChampBundle\Repository;

/**
 * NomEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomEquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
