<?php

namespace FDM\ChampBundle\Repository;

/**
 * StatRencontreEERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRencontreEERepository extends \Doctrine\ORM\EntityRepository
{
}
