<?php

namespace FDM\ChampBundle\Repository;

/**
 * StatRencontreEDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRencontreEDRepository extends \Doctrine\ORM\EntityRepository
{
}
